config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  namespace :api do 
    resources :batches, only: [:index]
    resources :users, only: [:update]
    get '/users/current_user', to: 'users#current_logged_in_user'
  end
  
  get '/terms_of_service', to: 'static_pages#terms_of_service'
  get '/payment_terms_of_service', to: 'static_pages#payment_terms_of_service'
  
  root to: "static_pages#home"
end

app/models/batch.rb
# == Schema Information
#
# Table name: batches
#
#  id              :integer          not null, primary key
#  name_of_beer    :string           not null
#  type_of_brewing :string           not null
#  gallons         :integer          not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Batch < ActiveRecord::Base
  belongs_to :user
end

app/models/ingredient.rb
# == Schema Information
#
# Table name: ingredients
#
#  id                 :integer          not null, primary key
#  ingredient_name    :string           not null
#  type_of_ingredient :string           default(""), not null
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

class Ingredient < ActiveRecord::Base
end

app/models/ingredient_usage.rb
# == Schema Information
#
# Table name: ingredient_usages
#
#  id               :integer          not null, primary key
#  ingredient_id    :integer          not null
#  batch_id         :integer          not null
#  quantity         :string           not null
#  time_of_addition :string           not null
#  stage_of_brewing :string           not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class IngredientUsage < ActiveRecord::Base
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  first_name             :string
#  last_name              :string
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :batches, dependent: :destroy
end

app/controllers/api/batches_controller.rb
class Api::BatchesController < ApplicationController
  def index 
    batches = current_user.batches
    render json: {batches: batches}
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  before_action :authenticate_user!, except: [:current_logged_in_user]
  
  def current_logged_in_user
    @user = current_user
    if @user.nil?
      render json: {message: "nope"}
    else
      render 'api/users/show'
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.email == "guest@example.com"
      render json: {message: "unable to update guest's email address.  you will break the matrix if you do.", status: 500}
    else
      if @user.update_attributes(user_params)
        render :show
      else
        render json: {message: "something went wrong server side updating the user", errors: @user.errors.full_messages, status: 400}
      end
    end
  end
  
  private 
  
  def user_params
    params.require(:user).permit(:id, :first_name, :last_name, :email)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :authenticate_user!
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
  end
  
  def terms_of_service
  end
  
  def payment_terms_of_service
  end
  
end

app/helpers/api/batches_helper.rb
module Api::BatchesHelper
end

app/helpers/api/users_helper.rb
module Api::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BrewersNotebook</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  
  <!-- Latest compiled and minified Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css">
	
	<link href='https://fonts.googleapis.com/css?family=Raleway:100,400' rel='stylesheet' type='text/css'>
</head>
<body id="main">


<div class="container-fluid" style="padding:0">
	<% if notice %>
		<p class="notice"><%= notice %></p>
	<% end %>
	<% if alert %>
		<p class="alert"><%= alert %></p>
	<% end %>

	<%= yield %>
</div>


<script>
  //manually remove alerts/notices from devise
  $(function(){
    setTimeout(function(){
      $(".notice").addClass("display-none");
    }, 3000);
    setTimeout(function(){
      $(".alert").addClass("display-none");
    }, 3000);
  });
</script>
</body>
</html>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" style="margin-bottom: 0px">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Brewer&#39;s Notebook</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
				<% if user_signed_in? %>
					<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
				<% else %>
					<li><%= link_to "Sign In", new_user_session_path %></li>
					<li><%= link_to "Sign Up", new_user_registration_path %></li>
				<% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
		
  </div><!-- /.container-fluid -->
</nav>

app/views/partials/_sign_up_disclaimer.html.erb
<div style="margin-top:10px;margin-bottom:10px">
	<p className="terms-agreement">
		By signing up I agree to Brewer&#39;s&nbsp;Notebook 
		<%= link_to "Terms of Service", terms_of_service_url, target: "_blank" %> 
		and&nbsp;
		<%= link_to "Payment Terms of Service", payment_terms_of_service_url, target: "_blank" %>
	</p>
</div>

app/views/static_pages/home.html.erb
<div id="root">
	
</div>